name: grid_point_4
description: Package that helps to implements the 4-point grid system in Flutter.
version: 1.0.0
homepage: https://github.com/jesusrp98/grid_point_4

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gap: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
